package murlen.util.fscript;

import java.util.HashMap;

import app.android.kopper.dslrscripting.RException;


/**
 * <p>FSException - Exception generated by FScript</p>
 * <p>
 * <I>Copyright (C) 2000 murlen.</I></p>
 * <p>
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.</p>
 * <p>
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.</p>
 *
 * <p>You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA </p>
 *
 * <p> This is a simple extension of exception - used to indicate error
 * conditions within FScript </p>
 * @author murlen
 * @version 1.12
 */

public class FSException extends RException {

    protected int messageKey;
    private final Object[] messageParams;

	protected int lineNo;
	protected String line;
	protected LexAnn tok;
	protected HashMap vars;
	protected HashMap gVars;

	public FSException(int messageKey, int lineNo, String line, LexAnn tok, HashMap vars, HashMap gVars,Object ... messageParams) {
        super(messageKey,messageParams);
        this.messageKey=messageKey;
        this.messageParams=messageParams;
        this.lineNo=lineNo;
		this.line=line;
		this.tok=tok;
		this.vars=vars;
		this.gVars=gVars;
	}

    public int getLineNo() {
        return lineNo;
    }

    public String getLine() {
        return line;
    }

    //
//    @Override
//    public String getMessage() {
//        return message+"\nline:" + lineNo+ "\n" + line ;
//    }
//
//    @Override
//	public String toString() {
//		return message + " (line:" + lineNo+ " [" + line + "])";
//	}
}

