package app.android.kopper.dslrscripting.constants;

/**
 * Created by kopper on 2015-02-07.
 * (C) Copyright 2015 kopperek@gmail.com
 * <p/>
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Lesser General Public License
 * (LGPL) version 2.1 which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-2.1.html
 * <p/>
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY); without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 */
public enum DeviceProp {
    BATTERY_LEVEL(0x5001),
    IMAGE_SIZE(0x5003),
    COMPRESSION_SETTING(0x5004),
    WHITE_BALANCE(0x5005),
    FNUMBER(0x5007),
    FOCAL_LENGTH(0x5008),
    FOCUS_MODE(0x500A),
    EXPOSURE_METERING_MODE(0x500B),
    FLASH_MODE(0x500C),
    EXPOSURE_TIME(0x500D),
    EXPOSURE_PROGRAM_MODE(0x500E),
    EXPOSURE_INDEX(0x500F),
    EXPOSURE_BIAS_COMPENSATION(0x5010),
    DATE_TIME(0x5011),
    STILL_CAPTURE_MODE(0x5013),
    BURST_NUMBER(0x5018),
    FOCUS_METERING_MODE(0x501C),
    RESET_SHOOTING_MENU(0xD015),
    WB_TUNE_AUTO(0xD017),
    WB_TUNE_INCANDESCENT(0xD018),
    WB_TUNE_FLUORESCENT(0xD019),
    WB_TUNE_SUNNY(0xD01A),
    WB_TUNE_FLASH(0xD01B),
    WB_TUNE_CLOUDY(0xD01C),
    WB_TUNE_SHADE(0xD01D),
    WB_PRESET_DATA_NO(0xD01F),
    WB_PRESET_DATA_VALUE0(0xD025),
    WB_PRESET_DATA_VALUE1(0xD026),
    COLOR_SPACE(0xD032),
    VIDEO_MODE(0xD036),
    EFFECT_MODE(0xD037),
    ISOAUTO_CONTROL(0xD054),
    EXPOSURE_EVSTEP(0xD056),
    AF_AT_LIVE_VIEW(0xD05D),
    AF_MODE_AT_LIVE_VIEW(0xD061),
    AUTO_OFF_TIME(0xD066),
    NOISE_REDUCTION(0xD06B),
    NOISE_REDUCTION_HI_ISO(0xD070),
    BRACKETING_TYPE(0xD078),
    ENABLE_SHUTTER(0xD08A),
    IMAGE_SENSOR_CLEANING(0xD08F),
    COMMENT_STRING(0xD090),
    ENABLE_COMMENT(0xD091),
    ORIENTATION_SENSOR_MODE(0xD092),
    MOVIE_RECORD_SCREEN_SIZE(0xD0A0),
    MOVIE_RECORD_MICROPHONE_LEVEL(0xD0A2),
    MOVIE_REC_PROHIBITION_CONDITION(0xD0A4),
    ENABLE_BRACKETING(0xD0C0),
    AEBRACKETING_STEP(0xD0C1),
    AEBRACKETING_PATTERN(0xD0C2),
    AEBRACKETING_COUNT(0xD0C3),
    WBBRACKETING_STEP(0xD0C4),
    WBBRACKETING_PATTERN(0xD0C5),
    ADLBRACKETING_PATTERN(0xD0C6),
    LENS_ID(0xD0E0),
    LENS_SORT(0xD0E1),
    LENS_TYPE(0xD0E2),
    LENS_FOCAL_MIN(0xD0E3),
    LENS_FOCAL_MAX(0xD0E4),
    LENS_APATURE_MIN(0xD0E5),
    LENS_APATURE_MAX(0xD0E6),
    AUTO_DISTORTION(0xD0F8),
    SCENE_MODE(0xD0F9),
    SHUTTER_SPEED(0xD100),
    EXTERNAL_DC_IN(0xD101),
    WARNING_STATUS(0xD102),
    REMAINING_EXPOSURE(0xD103),
    AFLOCK_STATUS(0xD104),
    AELOCK_STATUS(0xD105),
    FVLOCK_STATUS(0xD106),
    FOCUS_AREA(0xD108),
    FLEXIBLE_PROGRAM(0xD109),
    RECORDING_MEDIA(0xD10B),
    ORIENTATION(0xD10E),
    EXTERNAL_SPEED_LIGHT_EXIST(0xD120),
    EXTERNAL_SPEED_LIGHT_STATUS(0xD121),
    EXTERNAL_SPEED_LIGHT_SORT(0xD122),
    FLASH_COMPENSATION(0xD124),
    NEW_EXTERNAL_SPEED_LIGHT_MODE(0xD125),
    INTERNAL_FLASH_COMPENSATION(0xD126),
    HDRMODE(0xD130),
    HDREV(0xD131),
    HDRSMOOTHING(0xD132),
    ACTIVE_D_LIGHTING(0xD14E),
    WB_TUNE_FLUORESCENT_TYPE(0xD14F),
    AFMODE_SELECT(0xD161),
    ISOAUTO_SHUTTER_TIME(0xD164),
    ISOAUTO_SETTING(0xD16A),
    REMOTE_CONTROL_DELAY(0xD16B),
    INTERNAL_FLASH_MANUAL(0xD16D),
    ISOAUTO_HIGH_LIMIT(0xD183),
    LIVE_VIEW_STATUS(0xD1A2),
    LIVE_VIEW_IMAGE_ZOOM_RATIO(0xD1A3),
    LIVE_VIEW_PROHIBITION_CONDITION(0xD1A4),
    EXPOSURE_DISPLAY_STATUS(0xD1B0),
    EXPOSURE_INDICATE_STATUS(0xD1B1),
    INFO_DISPLAY_ERROR_STATUS(0xD1B2),
    EXPOSURE_INDICATE_LIGHTUP(0xD1B3),
    CONTINUOUS_SHOOTING_COUNT(0xD1B4),
    AUTO_SCENE_MODE_STATUS(0xD1B5),
    INTERNAL_FLASH_POPUP(0xD1C0),
    INTERNAL_FLASH_STATUS(0xD1C1),
    APPLICATION_MODE(0xD1F0),
    EXPOSURE_REMAINIG(0xD1F1),
    ACTIVE_PIC_CTRL_ITEM(0xD200),
    CHANGE_PIC_CTRL_ITEM(0xD201),
    USE_DEVICE_STAGE_FLAG(0xD303),
    SESSION_INITIATOR_VERSION_INFO(0xD406),
    PERCEIVED_DEVICE_TYPE(0xD407),;

    private final int code;


    DeviceProp(int code) {
        this.code=code;
    }

    public int getCode() {
        return code;
    }
}
